/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.eriklievaart.blog.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NL = 3;
  /** RegularExpression Id. */
  int TEXT = 4;
  /** RegularExpression Id. */
  int ANNOTATION_OPEN = 5;
  /** RegularExpression Id. */
  int ANNOTATION_CLOSE = 6;
  /** RegularExpression Id. */
  int UNKNOWN = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<NL>",
    "<TEXT>",
    "<ANNOTATION_OPEN>",
    "<ANNOTATION_CLOSE>",
    "<UNKNOWN>",
  };
}
